//
//  SearchRouter.swift
//  itunesTest
//
//  Created by Rodrigo Astorga on 19-02-20.
//  Copyright (c) 2020 Rodrigo Astorga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic
{
    func routeToSearchDetail(segue: UIStoryboardSegue?)
}

protocol SearchDataPassing
{
    var dataStore: SearchDataStore? { get }
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing
{
    weak var viewController: SearchViewController?
    var dataStore: SearchDataStore?
  
    // MARK: Routing

    func routeToSearchDetail(segue: UIStoryboardSegue?)
    {
      if let segue = segue {
        let destinationVC = segue.destination as! SearchDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSearchDetail(source: dataStore!, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "SearchDetailViewController") as! SearchDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSearchDetail(source: dataStore!, destination: &destinationDS)
        navigateToSearchDetail(source: viewController!, destination: destinationVC)
      }
    }

  // MARK: Navigation
  
    func navigateToSearchDetail(source: SearchViewController, destination: SearchDetailViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToSearchDetail(source: SearchDataStore, destination: inout SearchDetailDataStore)
    {
        let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
        let media = source.mediaResult?[selectedRow!]
        destination.media = media
    }
}
