//
//  SearchModels.swift
//  itunesTest
//
//  Created by Rodrigo Astorga on 19-02-20.
//  Copyright (c) 2020 Rodrigo Astorga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search
{
    // MARK: Use cases
    
    enum FetchSearch
    {
        struct Request
        {
            let searchString: String
        }
        struct Response
        {
            var media: [MediaResult]
        }
        struct ViewModel
        {
            struct DisplayedSearch {
                var trackName: String
                var artistName: String
                var genre: String
                var artworkURL: URL
                
                init(withMediaResult media: MediaResult) {
                    trackName = media.trackName ?? ""
                    artistName = media.artistName ?? ""
                    genre = media.primaryGenreName ?? ""
                    artworkURL = media.artworkUrl60 ?? URL(string: "")!
                }
            }
            
            var displayedSearch: [DisplayedSearch]
        }
    }
}
