//
//  SearchPresenter.swift
//  itunesTest
//
//  Created by Rodrigo Astorga on 19-02-20.
//  Copyright (c) 2020 Rodrigo Astorga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic
{
    func presentFetchedSearch(response: Search.FetchSearch.Response)
    func presentError(responseError: SearchError)
}

class SearchPresenter: SearchPresentationLogic
{
    weak var viewController: SearchDisplayLogic?
    
    // MARK: Do something
    func presentFetchedSearch(response: Search.FetchSearch.Response)
    {
        var displayedSearchResult: [Search.FetchSearch.ViewModel.DisplayedSearch] = []
        for resultSearch in response.media {
            
            let displayedSearch = Search.FetchSearch.ViewModel.DisplayedSearch(withMediaResult: resultSearch)
            displayedSearchResult.append(displayedSearch)
        }
        
        let viewModel = Search.FetchSearch.ViewModel(displayedSearch: displayedSearchResult)
        viewController?.displayFetchedSearch(viewModel: viewModel)
    }
    
    func presentError(responseError: SearchError) {
        viewController?.displayError(responseError: responseError)
    }
}
