//
//  SearchDetailPresenter.swift
//  itunesTest
//
//  Created by Rodrigo Astorga on 23-02-20.
//  Copyright (c) 2020 Rodrigo Astorga. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchDetailPresentationLogic
{
  func presentDetailSearch(response: SearchDetail.FetchDetail.Response)
}

class SearchDetailPresenter: SearchDetailPresentationLogic
{
  weak var viewController: SearchDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentDetailSearch(response: SearchDetail.FetchDetail.Response)
  {
    let detailSearch = SearchDetail.FetchDetail.ViewModel.DetailSearch(title: "title", bandName: "bandName", albumName: "albumName", artwork: URL(string: "asdf")!)
    let viewModel = SearchDetail.FetchDetail.ViewModel(detailSearch: detailSearch)
    viewController?.displayDetailSearch(viewModel: viewModel)
  }
}
